### ISSUE TITLE
Stun server needed ?

### ISSUE THREAD

**Issue by mielune** [lesmana/webrtc-without-signaling-server#4]
I saw that a stun server is defined is configuration :
Does it is really needed ?

```
 configuration = {
    iceServers: [{
      urls: "stun:stun.stunprotocol.org"}]};
  try {
    peerConnection = new RTCPeerConnection(configuration);
  } catch(err) {
    chatlog('error: ' + err);
  }
```

**Comment by lesmana** [comment]
a stun server is needed if there is a network address translation (NAT) between you and the peer you are trying to connect to. that is practically always the case if you are trying to connect over the internet. if you and your peer are in the same local network (typically without NAT) then you don't need a stun server and thus not need the configuration object.

https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/RTCPeerConnection (search for "iceServers")

**Comment by lesmana** [comment]
a stun server is needed if there is a network address translation (NAT) between you and the peer you are trying to connect to. that is practically always the case if you are trying to connect over the internet. if you and your peer are in the same local network (typically without NAT) then you don't need a stun server and thus not need the configuration object.

https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/RTCPeerConnection (search for "iceServers")

**Comment by mielune** [comment]
Thank you @lesmana for the doc entry.

I removed the configuration for ice Servers in your example code:

```js
function createPeerConnection(lasticecandidate) {
  configuration = {
    // iceServers: [
    //   { urls: "stun:stun.stunprotocol222.org"}
    // ]
  }
  try {
    peerConnection = new RTCPeerConnection(configuration);
  } catch(err) {
    chatlog('error: ' + err);
  }
```

But each peers failed with this error in the console:

`WebRTC: ICE failed, add a STUN server and see about:webrtc for more details`

![image](https://user-images.githubusercontent.com/8350742/163825841-1b9a72e3-c7ef-4163-921f-91811a91b453.png)

Any idea how to bypass the ice control ?

**Comment by mielune** [comment]
Hi again,

I made a lot of more tests and found that it is not working on Firefox only ! Using Chrome or Edge it is working fine.
Don't know why Firefox failed on that use case.

**Comment by lesmana** [comment]
thank you for the effort. during my time developing this i noticed sporadic problems connecting using some or other browser over internet or local network. i never tested rigorously so was not able to say which exact combination under which circumstance was problematic. it has been long time since i worked on this. sorry i cannot help you further.

**Comment by mielune** [comment]
Hi @lesmana and thank you for your replay.

I did some more tests and removing `iceServers` from configuration does'nt work with Firefox when offer and answer are in the same Firefox instance and in some other cases, thank's for your replay.

**Comment by anion155** [comment]
@mielune removing stun server configuration in chrome just make you use default one configured by browser
