### ISSUE TITLE
"without signalling server"

### ISSUE THREAD

**Issue by Quotatron3000** [lesmana/webrtc-without-signaling-server#5]
"a stun server is still used"

Then it isn't without a signalling server.

**Comment by PetrKubes97** [comment]
Stun server is not a signalling server.

**Comment by lesmana** [comment]
the stun server is not a signaling server.

i do not have hard proof but perhaps these articles will convince you:
https://webrtchacks.com/stun-helps-webrtc-traverse-nats/
https://bloggeek.me/webrtcglossary/stun/

in short: when you want to connect over the internet both parties need to know the internet facing adress of the other. a stun server is used to get the internet facing adress. a signaling server is then used to get that info (along with other info) to the other party.
